# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##########################################################################################
# Be sure to edit the values below
##########################################################################################

title: Search.gov
email: search@support.digitalgov.gov
description: >- # this means to ignore newlines until "baseurl:"
  Agency Name (EAC) Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Aenean et sapien a leo auctor scelerisque quis nec magna. Sed dictum ante a risus vehicula facilisis.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://example.gov" # the base hostname & protocol for your site, e.g. http://example.com

# Twitter handle. Only the handle, not the URL.
twitter: 18F

#################################################################
#
# Digital Analytics Program (DAP) configuration
#
# USAID   - Agency for International Development
# USDA    - Department of Agriculture
# DOC     - Department of Commerce
# DOD     - Department of Defense
# ED      - Department of Education
# DOE     - Department of Energy
# HHS     - Department of Health and Human Services
# DHS     - Department of Homeland Security
# HUD     - Department of Housing and Urban Development
# DOJ     - Department of Justice
# DOL     - Department of Labor
# DOS     - Department of State
# DOI     - Department of the Interior
# TREAS   - Department of the Treasury
# DOT     - Department of Transportation
# VA      - Department of Veterans Affairs
# EPA     - Environmental Protection Agency
# EOP     - Executive Office of the President
# GSA     - General Services Administration
# NASA    - National Aeronautics and Space Administration
# NARA    - National Archives and Records Administration
# NSF     - National Science Foundation
# NRC     - Nuclear Regulatory Commission
# OPM     - Office of Personnel Management
# USPS    - Postal Service
# SBA     - Small Business Administration
# SSA     - Social Security Administration
#
#################################################################
dap:
  # agency: your-agency

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: Get Started
    children:
      - name: Sign Up/Create an Account
        url: "/get-started/account.html"
      - name: Why Search.gov
        url: "#"
      - name: Site Launch Guide
        url: "/get-started/site-launch-guide.html"
      - name: "Going live with Search.gov: Checklist"
        url: "/get-started/go-live.html"
      - name: Regular Search Results and API-Results
        url: "/hosted-vs-api-results.html"
      - name: Available Search Features
        url: "/get-started/site-launch-guide.html#add-features"
  - name: Manage Your Search Site
    children:
      - name: Manage your search configuration in the Admin Center
        url: "/admin-center/index.html"
      - name: Add/remove users
        url: "/admin-center/dashboard/users.html"
      - name: Add a site
        url: "/admin-center/dashboard/add-site.html"
      - name: Add domains
        url: "/admin-center/content/domains.html"
      - name: Manage your search analytics
        url: "/admin-center/analytics/index.html"
      - name: Add search features
        url: "/get-started/site-launch-guide.html#add-features"
  - name: Index with Search.gov
    children:
      - name: What Search.gov indexes from your website
        url: "/indexing/what-searchgov-indexes.html"
      - name: How Search.gov ranks your search results
        url: "/indexing/ranking-factors.html"
      - name: How a page on a sitemap becomes a search result
        url: "/indexing/sitemaps-to-search-sites.html"
      - name: Step-by-step indexing workflow
        url: "/get-started/site-launch-guide.html#indexing-workflow"
      - name: Metadata and tags you should include in your website
        url: "/indexing/metadata.html"
      - name: Update your search after a redesign, CMS migration or both
        url: "/indexing/redesign.html"
  - name: About Us
    children:
      - name: About Us
        url: "/about/"
      - name: Customers
        url: "/about/customers.html"
      - name: Search.gov in Policy
        url: "/about/policy/"
      - name: Submit Feature Requests
        url: "/about/feedback"
      - name: Our Product Roadmap
        url: "/about/updates/roadmap/"
      - name: Release Notes
        url: "/tagged/release-notes/"
      - name: For Developers
        url: "/developer/"
# Sidebar configuration
#
# A sidebar of up to 3 levels can be configured here
# and included in the page by adding a `sidenav` property
# to the front matter that corresponds to the key defined here.
# Example:
# Adding the property `sidenav: admin_center` to a page will
# import the `admin_center` navigation defined below. If no
# `sidenav` property is specified, no sidebar will appear on the page

admin_center:
  - name: Activate
    url: /admin-center/activate/
  - name: Analytics
    url: /admin-center/analytics/
  - name: Content
    url: /admin-center/content/
  - name: Dashboard
    url: /admin-center/dashboard/
  - name: Display
    url: /admin-center/display/

site_launch_guide:
  - name: Add a Site
    url: /get-started/site-launch-guide/#add-site
  - name: Add Domains
    url: /get-started/site-launch-guide/#add-domains
  - name: Web Index Selection
    url: /get-started/site-launch-guide/#select-index 
  - name: Add Search Features
    url: /get-started/site-launch-guide/#add-features
  - name: Toggle Search Features On
    url: /get-started/site-launch-guide/#turn-features-on
  - name: Configure Results Page
    url: /get-started/site-launch-guide/#configure-branding
  - name: Connect Your Search Box to Search.gov
    url: /get-started/site-launch-guide/#go-live

about_us:
  - name: About Us
    url: "/about/"
  - name: Customers
    url: "/about/customers.html"
  - name: Search.gov in Policy
    url: "/about/policy/"
  - name: Submit Feature Requests
    url: "/about/feedback"
  - name: Our Product Roadmap
    url: "/about/updates/roadmap/"
  - name: Release Notes
    url: "/tagged/release-notes/"
  - name: For Developers
    url: "/developer/"

developer:
  - name: Indexing API
    url: "/developer/indexing-api.html"
    children:
      children:
          - name: Getting Started with i14y
            url: "/developer/i14y.html"
          - name: i14y Drawers
            url: "/developer/i14y-drawers.html"
          - name: i14y Testing
            url: "/developer/i14y-testing.html"
  - name: Jobs
    url: "/developer/jobs"

indexing:
  - name: Index with Search.gov
    children:
      - name: How does indexing work?
        children:
          - name: How search engines index your website
            url: "/get-started/training.html#how-engines-index"
          - name: What Search.gov indexes from your website
            url: "/indexing/what-searchgov-indexes.html"
          - name: How Search.gov ranks your search results
            url: "/indexing/ranking-factors.html"
          - name: How A Page on a Sitemap Becomes a Search
            url: "/indexing/sitemaps-to-search-sites.html"
          - name: A step-by-step indexing workflow
            url: "/indexing/"
      - name: Domain Level SEO Supports
        children:
          - name: All about XML sitemaps
            url: "LINK"
          - name: Robots.txt files
            url: "LINK"
      - name: Page Level SEO Supports
        children:
          - name: Metadata and tags you should include in your website
            url: "LINK"
          - name: How to get search engines to index the right content for better discoverability
            url: "LINK"

highlights:
  - heading: Highly configurable
    copy: No developers required - use our easy interface to design your search experience yourself, including what content to search, recommended content, and the look and feel of your search results page.
  - heading: Built for government
    copy: Because we only engage with government clients, we orient ourselves around your needs, whether it is security, compliance, search results coverage, or the unique circumstances of government web publishing.
  - heading: Hands-on customer service
    copy: Our team is available to help you with your questions, ranging from technical support to search engine optimization.
  - heading: No commitment necessary
    copy: There is no charge to use Search.gov, and we offer unlimited queries to our federal agency partners. 

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:

  # You should not change this.
  endpoint: https://search.usa.gov

  # replace this with your search.gov account
  affiliate: federalist-uswds-example

  # replace with your access key
  access_key: xX1gtb2RcnLbIYkHAcB6IaTRr4ZfN-p16ofcyUebeko=

  # this renders the results within the page instead of sending to user to search.gov
  inline: true

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

collections:
  pages:
    output: true
    permalink: /:path/

permalink: /:categories/:title.html

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

############################################################
# Plugin config
############################################################
paginate_per_page: 10
posts_paginate_path: blog/page:num
posts_paginate_layout: paginate
posts_tag_layout: tag

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: "posts"
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 3
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/page/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: "posts"
  # Optional, the default tag to use, omit to disable
  tag: ""
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""
  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index.html"

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock

assets:
  sources:
    - node_modules/uswds/dist/img
    - node_modules/uswds/dist/js
    - node_modules/uswds/dist/scss
    - node_modules/netlify-cms/dist
